name: Netease Recent Actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '00 22 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
      - uses: zonemeen/netease-recent-actions@v1.0.31
        with:
          id: '109096287'
          title: '最近在听'
